{
 "title": "Apigee Cloud",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   { "name": "region", "query": "dc-1" },
   { "name": "appDS", "label": "Application", "query": "influxdb" },
   { "name": "sysDS", "label": "System", "query": "influxdb" },
   { "name": "eventDS", "label": "Event", "query": "influxdb" },
   {
    "name": "color",
    "label": "Color",
    "query": "show tag values from heartbeats with key = \"dpcolor\" where region =~ /$region/"
   },
   {
    "name": "org",
    "label": "Org",
    "query": "show tag values from proxy with key = \"org\" where region =~ /$region/ "
   },
   {
    "name": "env",
    "label": "Env",
    "query": "show tag values from proxy with key = \"env\" WHERE org =~ /$org/ and region =~ /$region/"
   },
   {
    "name": "mppod",
    "label": "MPPod",
    "query": "show tag values from proxy with key = \"pod\" WHERE org = '$org' and env = '$env' and region = '$region'"
   },
   {
    "name": "rtpod",
    "label": "RTPod",
    "query": "show tag values from proxy with key = \"pod\" WHERE org =~ /$org/ and env = /$env/ and region = '$region'"
   }
  ]
 },
 "panels": [
  {
   "title": "Heartbeat ($color) (region = $region, org = $org, env = $env, mppod = $mppod, rtpod = $rtpod)",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "repeat": "color"
  },
  {
   "title": "Router (isUP)",
   "type": "graph",
   "gridPos": { "h": 4, "w": 8, "x": 0, "y": 1 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "$tag_host ($tag_release)",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "release" ], "type": "tag" },
      { "params": [ "host" ], "type": "tag" },
      { "params": [ "pod" ], "type": "tag" },
      { "params": [ "dpcolor" ], "type": "tag" },
      { "params": [ "release" ], "type": "tag" },
      { "params": [ "0" ], "type": "fill" }
     ],
     "measurement": "heartbeats",
     "query": "SELECT min(\"up\") FROM \"heartbeats\" WHERE \"service\" =~ /.*router/ AND \"dpcolor\" =~ /^$color$/ AND \"pod\" =~ /^$rtpod$/ AND $timeFilter GROUP BY time($interval), \"release\", \"host\", \"pod\", \"dpcolor\" fill(0)",
     "select": [
      [
       { "params": [ "up" ], "type": "field" },
       {
        "params": [],
        "type": "min"
       }
      ]
     ],
     "tags": [
      { "key": "service", "operator": "=~", "value": "/.*router/" },
      { "condition": "AND", "key": "dpcolor", "operator": "=~", "value": "/^$color$/" },
      { "condition": "AND", "key": "pod", "operator": "=~", "value": "/^$rtpod$/" }
     ]
    }
   ]
  },
  {
   "title": "Message Processor (isUP)",
   "type": "graph",
   "gridPos": { "h": 4, "w": 8, "x": 8, "y": 1 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "$tag_host ($tag_release)",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "host" ], "type": "tag" },
      { "params": [ "pod" ], "type": "tag" },
      { "params": [ "dpcolor" ], "type": "tag" },
      { "params": [ "service" ], "type": "tag" },
      { "params": [ "release" ], "type": "tag" },
      { "params": [ "0" ], "type": "fill" }
     ],
     "measurement": "heartbeats",
     "query": "SELECT min(\"up\") FROM \"heartbeats\" WHERE \"service\" =~ /.*message-processor/ AND \"dpcolor\" =~ /^$color$/ AND \"pod\" =~ /^$mppod$/ AND $timeFilter GROUP BY time($interval), \"host\", \"pod\", \"dpcolor\", \"service\" fill(0)",
     "select": [
      [
       { "params": [ "up" ], "type": "field" },
       {
        "params": [],
        "type": "min"
       }
      ]
     ],
     "tags": [
      { "key": "service", "operator": "=~", "value": "/.*message-processor/" },
      { "condition": "AND", "key": "dpcolor", "operator": "=~", "value": "/^$color$/" },
      { "condition": "AND", "key": "pod", "operator": "=~", "value": "/^$mppod$/" }
     ]
    }
   ]
  },
  {
   "title": "Message Processor (NAT Health)",
   "type": "graph",
   "gridPos": { "h": 4, "w": 8, "x": 16, "y": 1 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "$tag_host ($tag_release)",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "host" ], "type": "tag" },
      { "params": [ "pod" ], "type": "tag" },
      { "params": [ "dpcolor" ], "type": "tag" },
      { "params": [ "service" ], "type": "tag" },
      { "params": [ "release" ], "type": "tag" },
      { "params": [ "0" ], "type": "fill" }
     ],
     "measurement": "heartbeats",
     "query": "SELECT min(\"up\") FROM \"heartbeats\" WHERE \"service\" =~ /.*message-processor/ AND \"dpcolor\" =~ /^$color$/ AND \"pod\" =~ /^$mppod$/ AND $timeFilter GROUP BY time($interval), \"host\", \"pod\", \"dpcolor\", \"service\" fill(0)",
     "select": [
      [
       { "params": [ "health" ], "type": "field" },
       {
        "params": [],
        "type": "min"
       }
      ]
     ],
     "tags": [
      { "key": "service", "operator": "=~", "value": "/.*message-processor/" },
      { "condition": "AND", "key": "dpcolor", "operator": "=~", "value": "/^$color$/" },
      { "condition": "AND", "key": "pod", "operator": "=~", "value": "/^$mppod$/" }
     ]
    }
   ]
  },
  { "title": "Apigee Errors ($color)", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 5 }, "repeat": "color" },
  {
   "title": "Apigee Errors (router)",
   "type": "graph",
   "gridPos": { "h": 7, "w": 6, "x": 0, "y": 6 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "$tag_host ($tag_vhost)",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "dpcolor" ], "type": "tag" },
      { "params": [ "host" ], "type": "tag" },
      { "params": [ "vhost" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "upstream_apigee_errors",
     "query": "SELECT mean(\"rate\") FROM \"upstream_apigee_errors\" WHERE \"dpcolor\" =~ /^$color$/ AND \"org\" =~ /^$org$/ AND \"env\" =~ /^$env$/ AND \"region\" = '$region' AND $timeFilter GROUP BY time($interval), \"dpcolor\", \"host\" fill(null)",
     "select": [
      [
       { "params": [ "rate" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "1s" ], "type": "non_negative_derivative" }
      ]
     ],
     "tags": [
      { "key": "dpcolor", "operator": "=~", "value": "/^$color$/" },
      { "condition": "AND", "key": "org", "operator": "=~", "value": "/^$org$/" },
      { "condition": "AND", "key": "env", "operator": "=~", "value": "/^$env$/" }
     ]
    }
   ]
  },
  {
   "title": "Apigee Errors (mp)",
   "type": "graph",
   "gridPos": { "h": 7, "w": 6, "x": 6, "y": 6 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "$tag_host ($tag_proxy)",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "dpcolor" ], "type": "tag" },
      { "params": [ "host" ], "type": "tag" },
      { "params": [ "proxy" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "faults",
     "query": "SELECT non_negative_derivative(mean(\"apigee_errors\"), 1s) FROM \"faults\" WHERE \"dpcolor\" =~ /^$color$/ AND \"org\" =~ /^$org$/ AND \"env\" =~ /^$env$/ AND region= '$region' AND $timeFilter GROUP BY time($interval), \"dpcolor\", \"host\", \"proxy\" fill(null)",
     "select": [
      [
       { "params": [ "apigee_errors" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "1s" ], "type": "non_negative_derivative" }
      ]
     ],
     "tags": [
      { "key": "dpcolor", "operator": "=~", "value": "/^$color$/" },
      { "condition": "AND", "key": "org", "operator": "=~", "value": "/^$org$/" },
      { "condition": "AND", "key": "env", "operator": "=~", "value": "/^$env$/" }
     ]
    }
   ]
  },
  {
   "title": "Policy Errors (mp)",
   "type": "graph",
   "gridPos": { "h": 7, "w": 6, "x": 12, "y": 6 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "$tag_host ($tag_proxy)",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "dpcolor" ], "type": "tag" },
      { "params": [ "host" ], "type": "tag" },
      { "params": [ "proxy" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "faults",
     "query": "SELECT non_negative_derivative(mean(\"policy_errors\"), 1s) FROM \"faults\" WHERE \"dpcolor\" =~ /^$color$/ AND \"org\" =~ /^$org$/ AND \"env\" =~ /^$env$/ AND region= '$region' AND $timeFilter GROUP BY time($interval), \"dpcolor\", \"host\", \"proxy\" fill(null)",
     "select": [
      [
       { "params": [ "policy_errors" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "1s" ], "type": "non_negative_derivative" }
      ]
     ],
     "tags": [
      { "key": "dpcolor", "operator": "=~", "value": "/^$color$/" },
      { "condition": "AND", "key": "org", "operator": "=~", "value": "/^$org$/" },
      { "condition": "AND", "key": "env", "operator": "=~", "value": "/^$env$/" }
     ]
    }
   ]
  },
  {
   "title": "Target Errors (mp)",
   "type": "graph",
   "gridPos": { "h": 7, "w": 6, "x": 18, "y": 6 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "$tag_host ($tag_proxy)",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "dpcolor" ], "type": "tag" },
      { "params": [ "host" ], "type": "tag" },
      { "params": [ "proxy" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "faults",
     "query": "SELECT non_negative_derivative(mean(\"target_errors\"), 1s) FROM \"faults\" WHERE \"dpcolor\" =~ /^$color$/ AND \"org\" =~ /^$org$/ AND \"env\" =~ /^$env$/ AND region= '$region' AND $timeFilter GROUP BY time($interval), \"dpcolor\", \"host\", \"proxy\" fill(null)",
     "select": [
      [
       { "params": [ "target_errors" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "1s" ], "type": "non_negative_derivative" }
      ]
     ],
     "tags": [
      { "key": "dpcolor", "operator": "=~", "value": "/^$color$/" },
      { "condition": "AND", "key": "org", "operator": "=~", "value": "/^$org$/" },
      { "condition": "AND", "key": "env", "operator": "=~", "value": "/^$env$/" }
     ]
    }
   ]
  },
  {
   "title": "HTTP Status and Latency ($color)",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 13 },
   "repeat": "color"
  },
  {
   "title": "Router",
   "type": "graph",
   "gridPos": { "h": 7, "w": 6, "x": 0, "y": 14 },
   "yaxes": [
    { "format": "rps" }
   ],
   "targets": [
    {
     "alias": "200 $tag_host ($tag_vhost)",
     "groupBy": [
      { "params": [ "host" ], "type": "tag" },
      { "params": [ "vhost" ], "type": "tag" }
     ],
     "measurement": "vhost",
     "query": "SELECT non_negative_derivative(sum(\"200\"), 1s) FROM \"vhost\" WHERE \"dpcolor\" =~ /^$color$/ AND \"org\" =~ /^$org$/ AND \"env\" =~ /^$env$/ AND $timeFilter GROUP BY time(1s), \"host\"",
     "select": [
      [
       { "params": [ "200" ], "type": "field" },
       { "params": [ "1s" ], "type": "non_negative_derivative" }
      ]
     ],
     "tags": [
      { "key": "dpcolor", "operator": "=~", "value": "/^$color$/" },
      { "condition": "AND", "key": "org", "operator": "=~", "value": "/^$org$/" },
      { "condition": "AND", "key": "env", "operator": "=~", "value": "/^$env$/" }
     ]
    },
    {
     "alias": "201 $tag_host ($tag_vhost)",
     "groupBy": [
      { "params": [ "host" ], "type": "tag" },
      { "params": [ "vhost" ], "type": "tag" }
     ],
     "measurement": "vhost",
     "query": "SELECT non_negative_derivative(sum(\"201\"), 1s) FROM \"vhost\" WHERE \"dpcolor\" =~ /^$color$/ AND \"org\" =~ /^$org$/ AND \"env\" =~ /^$env$/ AND $timeFilter GROUP BY time(1s),\"host\"",
     "select": [
      [
       { "params": [ "201" ], "type": "field" },
       { "params": [ "1s" ], "type": "non_negative_derivative" }
      ]
     ],
     "tags": [
      { "key": "dpcolor", "operator": "=~", "value": "/^$color$/" },
      { "condition": "AND", "key": "org", "operator": "=~", "value": "/^$org$/" },
      { "condition": "AND", "key": "env", "operator": "=~", "value": "/^$env$/" }
     ]
    },
    {
     "alias": "202 $tag_host ($tag_vhost)",
     "groupBy": [
      { "params": [ "host" ], "type": "tag" },
      { "params": [ "vhost" ], "type": "tag" }
     ],
     "measurement": "vhost",
     "query": "SELECT non_negative_derivative(sum(\"202\"), 1s) FROM \"vhost\" WHERE \"dpcolor\" =~ /^$color$/ AND \"org\" =~ /^$org$/ AND \"env\" =~ /^$env$/ AND $timeFilter GROUP BY time(1s),\"host\"",
     "select": [
      [
       { "params": [ "202" ], "type": "field" },
       { "params": [ "1s" ], "type": "non_negative_derivative" }
      ]
     ],
     "tags": [
      { "key": "dpcolor", "operator": "=~", "value": "/^$color$/" },
      { "condition": "AND", "key": "org", "operator": "=~", "value": "/^$org$/" },
      { "condition": "AND", "key": "env", "operator": "=~", "value": "/^$env$/" }
     ]
    },
    {
     "alias": "302 $tag_host ($tag_vhost)",
     "groupBy": [
      { "params": [ "host" ], "type": "tag" },
      { "params": [ "vhost" ], "type": "tag" }
     ],
     "measurement": "vhost",
     "query": "SELECT non_negative_derivative(sum(\"302\"), 1s) FROM \"vhost\" WHERE \"dpcolor\" =~ /^$color$/ AND \"org\" =~ /^$org$/ AND \"env\" =~ /^$env$/ AND $timeFilter GROUP BY time(1s), \"host\"",
     "select": [
      [
       { "params": [ "302" ], "type": "field" },
       { "params": [ "1s" ], "type": "non_negative_derivative" }
      ]
     ],
     "tags": [
      { "key": "dpcolor", "operator": "=~", "value": "/^$color$/" },
      { "condition": "AND", "key": "org", "operator": "=~", "value": "/^$org$/" },
      { "condition": "AND", "key": "env", "operator": "=~", "value": "/^$env$/" }
     ]
    },
    {
     "alias": "400 $tag_host ($tag_vhost)",
     "groupBy": [
      { "params": [ "host" ], "type": "tag" },
      { "params": [ "vhost" ], "type": "tag" }
     ],
     "measurement": "vhost",
     "query": "SELECT non_negative_derivative(sum(\"400\"), 1s) FROM \"vhost\" WHERE \"dpcolor\" =~ /^$color$/ AND \"org\" =~ /^$org$/ AND \"env\" =~ /^$env$/ AND $timeFilter GROUP BY time(1s),\"host\"",
     "select": [
      [
       { "params": [ "400" ], "type": "field" },
       { "params": [ "1s" ], "type": "non_negative_derivative" }
      ]
     ],
     "tags": [
      { "key": "dpcolor", "operator": "=~", "value": "/^$color$/" },
      { "condition": "AND", "key": "org", "operator": "=~", "value": "/^$org$/" },
      { "condition": "AND", "key": "env", "operator": "=~", "value": "/^$env$/" }
     ]
    },
    {
     "alias": "500 $tag_host ($tag_vhost)",
     "groupBy": [
      { "params": [ "host" ], "type": "tag" },
      { "params": [ "vhost" ], "type": "tag" }
     ],
     "measurement": "vhost",
     "query": "SELECT non_negative_derivative(sum(\"500\"), 1s) FROM \"vhost\" WHERE \"dpcolor\" =~ /^$color$/ AND \"org\" =~ /^$org$/ AND \"env\" =~ /^$env$/ AND $timeFilter GROUP BY time(1s),\"host\"",
     "select": [
      [
       { "params": [ "500" ], "type": "field" },
       { "params": [ "1s" ], "type": "non_negative_derivative" }
      ]
     ],
     "tags": [
      { "key": "dpcolor", "operator": "=~", "value": "/^$color$/" },
      { "condition": "AND", "key": "org", "operator": "=~", "value": "/^$org$/" },
      { "condition": "AND", "key": "env", "operator": "=~", "value": "/^$env$/" }
     ]
    },
    {
     "alias": "502 $tag_host ($tag_vhost)",
     "groupBy": [
      { "params": [ "host" ], "type": "tag" },
      { "params": [ "vhost" ], "type": "tag" }
     ],
     "measurement": "vhost",
     "query": "SELECT non_negative_derivative(sum(\"502\"), 1s) FROM \"vhost\" WHERE \"dpcolor\" =~ /^$color$/ AND \"org\" =~ /^$org$/ AND \"env\" =~ /^$env$/ AND $timeFilter GROUP BY time(1s),\"host\"",
     "select": [
      [
       { "params": [ "502" ], "type": "field" },
       { "params": [ "1s" ], "type": "non_negative_derivative" }
      ]
     ],
     "tags": [
      { "key": "dpcolor", "operator": "=~", "value": "/^$color$/" },
      { "condition": "AND", "key": "org", "operator": "=~", "value": "/^$org$/" },
      { "condition": "AND", "key": "env", "operator": "=~", "value": "/^$env$/" }
     ]
    }
   ]
  },
  {
   "title": "Message Processor(Total)",
   "type": "graph",
   "gridPos": { "h": 7, "w": 6, "x": 6, "y": 14 },
   "yaxes": [
    { "format": "rps" }
   ],
   "targets": [
    {
     "alias": "$tag_host $tag_proxy",
     "groupBy": [
      { "params": [ "host" ], "type": "tag" },
      { "params": [ "proxy" ], "type": "tag" }
     ],
     "measurement": "proxy",
     "query": "SELECT non_negative_derivative(sum(\"total\"), 1s)/2 FROM \"proxy\" WHERE \"dpcolor\" =~ /^$color$/ AND \"org\" =~ /^$org$/ AND \"env\" =~ /^$env$/ AND $timeFilter GROUP BY time(1s), \"host\", \"proxy\"",
     "select": [
      [
       { "params": [ "total" ], "type": "field" },
       { "params": [ "1s" ], "type": "non_negative_derivative" }
      ]
     ],
     "tags": [
      { "key": "dpcolor", "operator": "=~", "value": "/^$color$/" },
      { "condition": "AND", "key": "org", "operator": "=~", "value": "/^$org$/" },
      { "condition": "AND", "key": "env", "operator": "=~", "value": "/^$env$/" }
     ]
    }
   ]
  },
  {
   "title": "Target",
   "type": "graph",
   "gridPos": { "h": 7, "w": 6, "x": 12, "y": 14 },
   "yaxes": [
    { "format": "rps" }
   ],
   "targets": [
    {
     "alias": "total $tag_target",
     "groupBy": [
      { "params": [ "target" ], "type": "tag" }
     ],
     "measurement": "target",
     "query": "SELECT non_negative_derivative(sum(\"total\"), 1s) FROM \"target\" WHERE \"dpcolor\" =~ /^$color$/ AND \"org\" =~ /^$org$/ AND \"env\" =~ /^$env$/ AND $timeFilter GROUP BY time(1s), \"target\"",
     "select": [
      [
       { "params": [ "2xx" ], "type": "field" },
       { "params": [ "1s" ], "type": "non_negative_derivative" }
      ]
     ]
    }
   ]
  },
  {
   "title": "Target Latency",
   "type": "graph",
   "gridPos": { "h": 7, "w": 6, "x": 18, "y": 14 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "alias": "$tag_target $tag_proxy",
     "groupBy": [
      { "params": [ "target" ], "type": "tag" },
      { "params": [ "proxy" ], "type": "tag" }
     ],
     "measurement": "target",
     "query": "SELECT mean(\"avg_latency\") FROM \"target\" WHERE \"dpcolor\" =~ /^$color$/ AND \"org\" =~ /^$org$/ AND \"env\" =~ /^$env$/ AND $timeFilter GROUP BY time($interval), \"target\", \"proxy\"",
     "select": [
      [
       { "params": [ "avg_latency" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "dpcolor", "operator": "=~", "value": "/^$color$/" },
      { "condition": "AND", "key": "org", "operator": "=~", "value": "/^$org$/" },
      { "condition": "AND", "key": "env", "operator": "=~", "value": "/^$env$/" }
     ]
    }
   ]
  },
  { "title": "HTTP Status Split ($color)", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 21 }, "repeat": "color" },
  {
   "title": "Message Processor (2xx)",
   "type": "graph",
   "gridPos": { "h": 7, "w": 6, "x": 0, "y": 22 },
   "yaxes": [
    { "format": "rps" }
   ],
   "targets": [
    {
     "alias": "$tag_host $tag_proxy",
     "groupBy": [
      { "params": [ "host" ], "type": "tag" },
      { "params": [ "proxy" ], "type": "tag" }
     ],
     "measurement": "proxy",
     "query": "SELECT non_negative_derivative(sum(\"2xx\"), 1s)/2  FROM \"proxy\" WHERE \"dpcolor\" =~ /^$color$/ AND \"org\" =~ /^$org$/ AND \"env\" =~ /^$env$/ AND $timeFilter GROUP BY time(1s), \"host\", \"proxy\"",
     "select": [
      [
       { "params": [ "2xx" ], "type": "field" },
       { "params": [ "1s" ], "type": "non_negative_derivative" }
      ]
     ],
     "tags": [
      { "key": "dpcolor", "operator": "=~", "value": "/^$color$/" },
      { "condition": "AND", "key": "org", "operator": "=~", "value": "/^$org$/" },
      { "condition": "AND", "key": "env", "operator": "=~", "value": "/^$env$/" }
     ]
    }
   ]
  },
  {
   "title": "Message Processor (3xx)",
   "type": "graph",
   "gridPos": { "h": 7, "w": 4, "x": 6, "y": 22 },
   "yaxes": [
    { "format": "rps" }
   ],
   "targets": [
    {
     "alias": "$tag_host $tag_proxy",
     "groupBy": [
      { "params": [ "host" ], "type": "tag" },
      { "params": [ "proxy" ], "type": "tag" }
     ],
     "measurement": "proxy",
     "query": "SELECT non_negative_derivative(sum(\"3xx\"), 1s)/2 FROM \"proxy\" WHERE \"dpcolor\" =~ /^$color$/ AND \"org\" =~ /^$org$/ AND \"env\" =~ /^$env$/ AND $timeFilter GROUP BY time(1s), \"host\", \"proxy\"",
     "select": [
      [
       { "params": [ "3xx" ], "type": "field" },
       { "params": [ "1s" ], "type": "non_negative_derivative" }
      ]
     ],
     "tags": [
      { "key": "dpcolor", "operator": "=~", "value": "/^$color$/" },
      { "condition": "AND", "key": "org", "operator": "=~", "value": "/^$org$/" },
      { "condition": "AND", "key": "env", "operator": "=~", "value": "/^$env$/" }
     ]
    }
   ]
  },
  {
   "title": "Message Processor (4xx)",
   "type": "graph",
   "gridPos": { "h": 7, "w": 4, "x": 10, "y": 22 },
   "yaxes": [
    { "format": "rps" }
   ],
   "targets": [
    {
     "alias": "$tag_host $tag_proxy",
     "groupBy": [
      { "params": [ "host" ], "type": "tag" },
      { "params": [ "proxy" ], "type": "tag" }
     ],
     "measurement": "proxy",
     "query": "SELECT non_negative_derivative(sum(\"4xx\"), 1s)/2 FROM \"proxy\" WHERE \"dpcolor\" =~ /^$color$/ AND \"org\" =~ /^$org$/ AND \"env\" =~ /^$env$/ AND $timeFilter GROUP BY time(1s),\"host\", \"proxy\"",
     "select": [
      [
       { "params": [ "4xx" ], "type": "field" },
       { "params": [ "1s" ], "type": "non_negative_derivative" }
      ]
     ],
     "tags": [
      { "key": "dpcolor", "operator": "=~", "value": "/^$color$/" },
      { "condition": "AND", "key": "org", "operator": "=~", "value": "/^$org$/" },
      { "condition": "AND", "key": "env", "operator": "=~", "value": "/^$env$/" }
     ]
    }
   ]
  },
  {
   "title": "Message Processor (5xx)",
   "type": "graph",
   "gridPos": { "h": 7, "w": 4, "x": 14, "y": 22 },
   "yaxes": [
    { "format": "rps" }
   ],
   "targets": [
    {
     "alias": "$tag_host $tag_proxy",
     "groupBy": [
      { "params": [ "host" ], "type": "tag" },
      { "params": [ "proxy" ], "type": "tag" }
     ],
     "measurement": "proxy",
     "query": "SELECT non_negative_derivative(sum(\"5xx\"), 1s)/2 FROM \"proxy\" WHERE \"dpcolor\" =~ /^$color$/ AND \"org\" =~ /^$org$/ AND \"env\" =~ /^$env$/ AND $timeFilter GROUP BY time(1s),\"host\", \"proxy\"",
     "select": [
      [
       { "params": [ "5xx" ], "type": "field" },
       { "params": [ "1s" ], "type": "non_negative_derivative" }
      ]
     ],
     "tags": [
      { "key": "dpcolor", "operator": "=~", "value": "/^$color$/" },
      { "condition": "AND", "key": "org", "operator": "=~", "value": "/^$org$/" },
      { "condition": "AND", "key": "env", "operator": "=~", "value": "/^$env$/" }
     ]
    }
   ]
  },
  {
   "title": "Proxy Latency",
   "type": "graph",
   "gridPos": { "h": 7, "w": 6, "x": 18, "y": 22 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "$tag_target $tag_proxy",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT \"avg_latency\" FROM \"proxy\" WHERE \"dpcolor\" =~ /^$color$/ AND \"org\" =~ /^$org$/ AND \"env\" =~ /^$env$/ AND $timeFilter GROUP BY \"target\", \"proxy\"",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  { "title": "MP Health ($color)", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 29 }, "repeat": "color" },
  {
   "title": "Heap Used",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 30 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "alias": "$tag_host",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "host" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "heap",
     "select": [
      [
       { "params": [ "p_used" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "init" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "pod", "operator": "=~", "value": "/^$mppod$/" },
      { "condition": "AND", "key": "dpcolor", "operator": "=~", "value": "/^$color$/" }
     ]
    }
   ]
  },
  {
   "title": "Thread Count",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 30 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "alias": "$tag_host",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "host" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "threads",
     "query": "SELECT mean(\"count\") FROM \"threads\" WHERE \"pod\" =~ /^$mppod$/ AND \"dpcolor\" =~ /^$color$/ AND $timeFilter GROUP BY time($interval), \"host\" fill(null)",
     "select": [
      [
       { "params": [ "count" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "pod", "operator": "=~", "value": "/^$mppod$/" },
      { "condition": "AND", "key": "dpcolor", "operator": "=~", "value": "/^$color$/" }
     ]
    }
   ]
  },
  {
   "title": "NIO",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 30 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "$tag_host(Accepted)",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT mean(\"accepted\") FROM \"nio\" WHERE \"pod\" =~ /^$mppod$/ AND \"dpcolor\" =~ /^$color$/ AND $timeFilter GROUP BY time($interval), \"host\" fill(null)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "alias": "$tag_host (Conn Pending)",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT mean(\"conn_pending\") FROM \"nio\" WHERE \"pod\" =~ /^$mppod$/ AND \"dpcolor\" =~ /^$color$/ AND $timeFilter GROUP BY time($interval), \"host\" fill(null)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "alias": "$tag_host (Connected)",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT mean(\"connected\") FROM \"nio\" WHERE \"pod\" =~ /^$mppod$/ AND \"dpcolor\" =~ /^$color$/ AND $timeFilter GROUP BY time($interval), \"host\" fill(null)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  { "title": "Machine Stats ($color)", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 37 }, "repeat": "color" },
  {
   "title": "Load",
   "type": "graph",
   "gridPos": { "h": 7, "w": 6, "x": 0, "y": 38 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "$tag_host",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "type_instance" ], "type": "tag" },
      { "params": [ "host" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "system",
     "query": "SELECT mean(\"load1\") FROM \"system\" WHERE \"dpcolor\" =~ /^$color$/ AND region= '$region' AND pod = '$mppod' AND $timeFilter GROUP BY time($interval), \"type_instance\", \"host\" fill(null)",
     "select": [
      [
       { "params": [ "load1" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "dpcolor", "operator": "=~", "value": "/^$color$/" }
     ]
    }
   ]
  },
  {
   "title": "Network",
   "type": "graph",
   "gridPos": { "h": 7, "w": 6, "x": 6, "y": 38 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "alias": "Received $tag_host",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "host" ], "type": "tag" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "interface_rx",
     "query": "SELECT derivative(mean(\"packets_recv\"), 1s) FROM \"net\" WHERE $timeFilter AND region= '$region' AND pod = '$mppod' GROUP BY time($interval), \"host\" fill(none)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "1s" ], "type": "derivative" }
      ]
     ]
    },
    {
     "alias": "Sent $tag_host",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "host" ], "type": "tag" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "interface_tx",
     "query": "SELECT derivative(mean(\"packets_sent\"), 1s) FROM \"net\" WHERE $timeFilter AND region= '$region' AND pod = '$mppod' GROUP BY time($interval), \"host\" fill(none)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "1s" ], "type": "derivative" }
      ]
     ]
    }
   ]
  },
  {
   "title": "Memory",
   "type": "graph",
   "gridPos": { "h": 7, "w": 6, "x": 12, "y": 38 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "alias": "$tag_host",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "type_instance" ], "type": "tag" },
      { "params": [ "host" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "memory_value",
     "query": "SELECT mean(used) FROM \"mem\" WHERE $timeFilter AND region= '$region' AND pod = '$mppod' GROUP BY time($interval), \"host\" fill(null)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "type_instance", "operator": "=~", "value": "/.*/" }
     ]
    }
   ]
  },
  {
   "title": "Disk Space",
   "type": "graph",
   "gridPos": { "h": 7, "w": 6, "x": 18, "y": 38 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "alias": "$tag_host ($tag_path)",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "host" ], "type": "tag" },
      { "params": [ "path" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "disk",
     "query": "SELECT distinct(\"used_percent\") FROM \"disk\" WHERE (\"pod\" =~ /^$rtpod$/ OR \"pod\" =~ /^$mppod$/) AND \"path\" = '/' AND $timeFilter GROUP BY time($interval), \"host\", \"path\" fill(null)",
     "select": [
      [
       { "params": [ "used_percent" ], "type": "field" },
       {
        "params": [],
        "type": "distinct"
       }
      ]
     ],
     "tags": [
      { "key": "pod", "operator": "=~", "value": "/^$rtpod$/" },
      { "condition": "OR", "key": "pod", "operator": "=~", "value": "/^$mppod$/" }
     ]
    }
   ]
  },
  {
   "title": "Router Load",
   "type": "graph",
   "gridPos": { "h": 7, "w": 6, "x": 0, "y": 45 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "$tag_host",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "type_instance" ], "type": "tag" },
      { "params": [ "host" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "system",
     "query": "SELECT mean(\"load1\") FROM \"system\" WHERE \"dpcolor\" =~ /^$color$/ AND region= '$region' AND pod = '$rtpod' AND $timeFilter GROUP BY time($interval), \"type_instance\", \"host\" fill(null)",
     "select": [
      [
       { "params": [ "load1" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "dpcolor", "operator": "=~", "value": "/^$color$/" }
     ]
    }
   ]
  },
  {
   "title": "CPU (User)",
   "type": "graph",
   "gridPos": { "h": 7, "w": 6, "x": 6, "y": 45 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "alias": "$tag_host",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "host" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "cpu",
     "query": "SELECT mean(\"usage_user\") FROM \"cpu\" WHERE (\"pod\" =~ /^$rtpod$/ OR \"pod\" =~ /^$mppod$/) AND \"dpcolor\" =~ /^$color$/ AND $timeFilter GROUP BY time($interval), \"host\" fill(null)",
     "select": [
      [
       { "params": [ "usage_user" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "pod", "operator": "=~", "value": "/^$rtpod$/" },
      { "condition": "OR", "key": "pod", "operator": "=~", "value": "/^$mppod$/" },
      { "condition": "AND", "key": "dpcolor", "operator": "=~", "value": "/^$color$/" }
     ]
    }
   ]
  },
  {
   "title": "CPU (Guest)",
   "type": "graph",
   "gridPos": { "h": 7, "w": 6, "x": 12, "y": 45 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "alias": "$tag_host",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "host" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "cpu",
     "query": "SELECT mean(\"usage_guest\") FROM \"cpu\" WHERE (\"pod\" =~ /^$rtpod$/ OR \"pod\" =~ /^$mppod$/ ) AND \"dpcolor\" =~ /^$color$/ AND $timeFilter GROUP BY time($interval), \"host\" fill(null)",
     "select": [
      [
       { "params": [ "usage_guest" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "pod", "operator": "=~", "value": "/^$rtpod$/" },
      { "condition": "OR", "key": "pod", "operator": "=~", "value": "/^$mppod$/" },
      { "condition": "AND", "key": "dpcolor", "operator": "=~", "value": "/^$color$/" }
     ]
    }
   ]
  },
  {
   "title": "CPU (System)",
   "type": "graph",
   "gridPos": { "h": 7, "w": 6, "x": 18, "y": 45 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "alias": "$tag_host",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "host" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "cpu",
     "query": "SELECT distinct(\"used_percent\") FROM \"disk\" WHERE (\"pod\" =~ /^$rtpod$/ OR \"pod\" =~ /^$mppod$/) AND \"path\" = '/' AND $timeFilter GROUP BY time($interval), \"host\", \"path\" fill(null)",
     "select": [
      [
       { "params": [ "usage_system" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "pod", "operator": "=~", "value": "/^$rtpod$/" },
      { "condition": "OR", "key": "pod", "operator": "=~", "value": "/^$mppod$/" }
     ]
    }
   ]
  }
 ]
}